language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: eYsMfTKA67kWqG/LU9vDs2pU6I7srXIRtdvIQUO1XG2/tjtkeo3wsx0OSBtIelaXzMa9ElPfc/ma2Xenf3Uk8DgL1dGE5Sb0DMgNLolhBwvtwl1mr7PoEMYRw+R3bxOT7dTiwp8GdoQHhWUjzKmUUHH+nUtC66Cmhok825IqC4bJJGHEkE7tTwe9as36jssmybfQaX1xfwbal5Rx6tYxVJNi7bdcdPxweorQ4Tq3UVVdJl47Kl5aTNiLh39Gb4fZtBsKZ0pWiU1qcakzTQhmCFU3WoZBZgY5dfOqbT5CCYNSi33X2UifO8ip8zbBogBXsqiFtiQNvGzaxcKb2cbIaMmPMNmZ5sX5OBrwGDlWY5ZZ3eSczrM3b+Mr1AW3+4dVRhshJiiAkTpywsnxv6DLTBFse86GaPjfYEei7gfe4fLOjl7K60rCpyLsam8WrzwGnyMi1j0Jza82Q39R4OFPMqjMaTMDkjm3A/Z8Q5ffm/Os8FkaYuO/TwCkXl+vJrIhpfENiF18zjhoC/HukAR2of/YDbxs3qbGNJRhiElZ1DTUO6bIkK5/1SWe7zz3PyrGIlL7pC4CQaHgcZeAExH5GixDI2Gi1sHvTFjnH1/frXfDrS3APj5KEST5UfrNVOUrGxKDKs2drtnyLsFHpducLCUTxkkyxj4BzAij6AoAg8E=
  app: rocky-tundra-11063
  on:
    repo: seanphunt18/blog-app-continuous-integration
